### ISSUE TITLE
Read queries in a Rayon iterator

### ISSUE THREAD

**Issue by xosxos** [georgebarwood/RustDB#1]
I'm doing some high throughput bioinformatics and I use Rayon for parallelization. I have been looking for embedded databases (preferably relational) with good multithreading capabilities. What I'm doing is some heavy calculations on stdin data and then outputting results to stdout. Fetching annotations from a database is one step in the process.

I played around with RustDB and it is very fast and db sizes are in line with SQLite. However as the DB or Table structs are not Send, I am wondering if multithreaded reading in a Rayon iterator would ever be possible without creating a new db for each thread? As I understand RustDB wouldn't gain much from such additional parallelization, however this happens to often be the structure of Rayon multithreading.

```rust
use rayon::prelude::*;
use rustdb::{
    standard_builtins, AccessPagedData, AtomicFile, BuiltinMap, Database, GenTransaction,
    SharedPagedData, SimpleFileStorage,
};
use std::sync::Arc;

fn main() -> Result<()> {
    let file = Box::new(SimpleFileStorage::new("./test.rustdb"));
    let upd = Box::new(SimpleFileStorage::new("./test.upd"));
    let stg = Box::new(AtomicFile::new(file, upd));
    let spd = Arc::new(SharedPagedData::new(stg));
    let mut bmap = BuiltinMap::default();
    standard_builtins(&mut bmap);
    let bmap = Arc::new(bmap);
    let wapd = AccessPagedData::new_reader(spd);

    let db = Database::new(wapd, "", bmap);
    let table = db.table("my_schema", "my_table");

    let ids = (1..1_000_001).par_bridge().filter_map(|id| {
        if let Some((pp, off)) = table.id_get(&db, id) {
            let p = &pp.borrow();
            let a = table.access(p, off);
            Some(a.id())
        }
       None
    }).collect::<Vec<u64>>;

    Ok(())
}
```

**Comment by georgebarwood** [comment]
I think it would be possible to do multi-threaded reading as you suggest, although I haven't tried it.
Each thread would need to have its own reader and Database.
